/*
 Navicat Premium Data Transfer

 Source Server         : 551project
 Source Server Type    : MySQL
 Source Server Version : 80031 (8.0.31)
 Source Host           : localhost:3306
 Source Schema         : total

 Target Server Type    : MySQL
 Target Server Version : 80031 (8.0.31)
 File Encoding         : 65001

 Date: 11/04/2024 12:24:42
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for Books
-- ----------------------------
USE total;
DROP TABLE IF EXISTS `Books`;
CREATE TABLE `Books` (
  `book_id` int NOT NULL,
  `isbn` longtext,
  `author` longtext,
  `title` longtext,
  `publisher` longtext,
  `publication_year` int DEFAULT NULL,
  `subjects` longtext,
  PRIMARY KEY (`book_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----------------------------
-- Records of Books
-- ----------------------------
BEGIN;
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (1, '1481425730, 1481425749, 9781481425735, 9781481425742', 'O\'Ryan, Ellie', 'A tale of two friends / adapted by Ellie O\'Ryan ; illustrated by Tom Caulfield, Frederick Gardner, Megan Petasky, and Allen Tam.', 'Simon Spotlight,', 2014, 'Musicians Fiction, Bullfighters Fiction, Best friends Fiction, Friendship Fiction, Adventure and adventurers Fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (2, '144945867X, 9781449458676', 'Scott, Jerry, 1955-', 'Peace, love & Wi-Fi : a ZITS treasury / by Jerry Scott and Jim Borgman.', 'Andrews McMeel Publishing,', 2014, 'Duncan Jeremy Fictitious character Comic books strips etc, Teenagers United States Comic books strips etc, Parent and teenager Comic books strips etc, Families Comic books strips etc, Comic books strips etc, Comics Graphic works, Humorous comics');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (3, '0373789998, 037380394X, 9780373789993, 9780373803941', 'London, Julia', 'Hard-hearted Highlander / Julia London.', 'HQN,', 0, 'Man woman relationships Fiction, Betrothal Fiction, Governesses Fiction, Highlands Scotland Fiction, Romance fiction, Historical fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (4, '0062484877, 9780062484871', 'Olson, Kayla', 'The Sandcastle Empire / Kayla Olson.', 'HarperTeen,', 2017, 'Survival Juvenile fiction, Islands Juvenile fiction, Dystopias Juvenile fiction, Fantasy fiction, Young adult fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (5, NULL, NULL, 'Doctor Who. The return of Doctor Mysterio / BBC ; BBC Wales ; produced by Peter Bennett ; [written] by Steven Moffat ; directed by Ed Bazalgette.', 'BBC Worldwide,', 0, 'Doctor Fictitious character Drama, Time travel Drama, Human alien encounters Drama, Science fiction television programs, Fiction television programs, Television series, Video recordings for the hearing impaired');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (6, '1476755213, 9781476755212', 'Pyper, Andrew', 'The only child : a novel / Andrew Pyper.', 'Simon & Schuster,', 2017, 'Forensic psychiatrists Fiction, Psychological fiction, Thrillers Fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (7, '0763692921, 9780763692926', 'Duddle, Jonny', 'The Jolley-Rogers and the monster\'s gold / Jonny Duddle.', 'Templar Books, an imprint of Candelwick Press,', 2017, 'Pirates Juvenile fiction, Monsters Juvenile fiction, Treasure troves Juvenile fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (8, '1942556195, 9781942556190', NULL, 'Duke in his own words : John Wayne\'s life in letters, handwritten notes and never-before-seen photos / [introduction by Ethan Wayne].', 'Topix Media Lab,', 0, 'Wayne John 1907 1979 Correspondence, Wayne John 1907 1979, Motion picture actors and actresses United States Correspondence, Motion picture actors and actresses United States Biography');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (9, '1604695498, 9781604695496', 'Keville, Kathi', 'The aromatherapy garden : growing fragrant plants for happiness and well-being / Kathi Keville.', 'Timber Press,', 2016, 'Fragrant gardens, Aromatic plants Therapeutic use, Aromatherapy');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (10, NULL, NULL, 'Broadcasting yearbook--marketbook issue.', '[Broadcasting Publications],', 1960, 'Broadcast advertising United States Periodicals, Television broadcasting United States Periodicals, Radio broadcasting United States Periodicals');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (11, '0060774703, 0060774711, 9780060774707, 9780060774714', 'Boniface, William', 'The great powers outage / William Boniface ; illustrations by Stephen Gilpin.', 'HarperCollins,', 2008, 'Heroes Juvenile fiction, Criminals Juvenile fiction, Humorous stories');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (12, '823418073', 'Poydar, Nancy', 'Last day, hooray! / Nancy Poydar.', 'Holiday House,', 2004, 'Schools Fiction, Parties Fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (13, NULL, 'Rutherford, G. Scott, 1944-', 'Travel forecasting procedures to support the Puget Sound transportation alternatives analysis-- north corridor / prepared by G. Scott Rutherford, transportation and planning consultant ; Puget Sound Council of Governments ; for Urban Mass Transportation Administration.', '[The Council?],', 0, 'Transportation Washington State Puget Sound Region Forecasting Mathematical models, Trip generation Washington State Puget Sound Region Forecasting Mathematical models, Local transit Ridership Washington State Puget Sound Region Forecasting Mathematical models');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (14, '1439100195, 1439100217, 9781439100196, 9781439100219', 'Lamb-Shapiro, Jessica', 'Promise land : my journey through America\'s self-help culture / Jessica Lamb-Shapiro.', 'Simon & Schuster,', 2014, 'Self care Health, Self care Health Psychological aspects, Psychologists Psychology, Self management Psychology');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (15, '761419683', 'NgCheong-Lum, Roseline, 1962-', 'Haiti / Rosalie Ng Cheong-Lum & Leslie Jermyn.', 'Marshall Cavendish Benchmark,', 2005, 'Haiti Juvenile literature');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (16, '0316099171, 9780316099172', 'Harrison, Lisi', 'Back and deader than ever / a novel by Lisi Harrison.', 'Poppy/Little, Brown,', 2012, 'Monsters Juvenile fiction, High schools Juvenile fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (17, '0531220907, 9780531220900', 'Mara, Wil', 'Nicaragua / by Wil Mara.', 'Children\'s Press,', 0, 'Nicaragua Juvenile literature');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (18, '1910985139, 9781910985137', 'Wadey, Maggie', 'The English daughter / Maggie Wadey.', 'Sandstone Press Ltd,', 2016, 'Wadey Maggie Family, Kavanagh Agnes Teresa Childhood and youth, Kavanagh Agnes Teresa Anecdotes, Mother and child, Tipperary Ireland County Social life and customs 20th century, Autobiographies');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (19, NULL, 'United States. Congress. House. Committee on Energy and Commerce. Subcommittee on Health and the Environment', 'Acid precipitation : hearings before the Subcommittee on Health and the Environment of the Committee on Energy and Commerce, House of Representatives, Ninety-seventh Congress, first session, on effects and solutions to combat acid precipitation.', 'U.S. G.P.O.,', 1982, 'Acid rain United States, Acid pollution of rivers lakes etc United States');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (20, '385037651', 'Harman, Gilbert', 'On Noam Chomsky; critical essays.', 'Anchor Press,', 1974, 'Chomsky Noam, Linguistics Research United States');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (21, '087004401X', 'Nestor, Sandy', 'Our Native American legacy : Northwest towns with Indian names / Sandy Nestor.', 'Caxton Press,', 2001, 'Names Indian Northwest Pacific, Names Indian Alaska, Names Geographical Northwest Pacific, Names Geographical Alaska, Northwest Pacific History Local, Alaska History Local');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (22, '1941411452, 9781941411452', 'McGlynn, Karyna', 'Hothouse / Karyna McGlynn.', 'Sarabande Books,', 0, 'Poetry');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (23, '1429686596, 9781429686594', 'Caper, William', 'The U.S. Army Rangers : the missions / by William Caper.', 'Capstone Press,', 2013, 'United States Army Commando troops Juvenile literature');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (24, '1770492380, 9781770492387', NULL, 'Wishes and worries : coping with a parent who drinks too much alcohol / presented by the Centre for Addiction and Mental Health ; illustrated by Lars Rudebjer.', 'Tundra Books,', 2011, 'Children of alcoholics Juvenile literature, Alcoholics Family relationships Juvenile literature');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (25, '1250020204, 9781250020208', 'Rappaport, Helen', 'The Romanov sisters : the lost lives of the daughters of Nicholas and Alexandra / Helen Rappaport.', 'St. Martin\'s Press,', 2014, 'Nicholas II Emperor of Russia 1868 1918 Assassination, Nicholas II Emperor of Russia 1868 1918 Family Assassination, Romanov House of History 20th century Sources, Princesses Russia Biography Sources, Sisters');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (26, '0316219118, 0316219126, 9780316219112, 9780316219129', 'McClellan, Brian, 1986-', 'The autumn republic / Brian McClellan.', 'Orbit,', 2015, 'Kings and rulers Fiction, Imaginary wars and battles Fiction, Imaginary places Fiction, Betrayal Fiction, Wizards Fiction, Fantasy fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (27, '0785168346, 9780785168348', 'Gillen, Kieron', 'Iron Man. The secret origin of Tony Stark, Book 1 / writer, Kieron Gillen ; penciler, Greg Land (#6-8) ; artist, Dale Eaglesham (9-11) ; inker, Jay Leisten (#6-8) ; colorist, Guru-eFX ; letterer, VC\'s Joe Caramagna.', 'Marvel Worldwide, Inc.,', 2013, 'Iron Man Fictitious character Comic books strips etc, Superheroes Comic books strips etc, Science fiction comic books strips etc, Graphic novels, Superhero comic books strips etc');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (28, '9789862116326, 9862116323', 'Miyanishi, Tatsuya, 1956-', 'Da da da! Die di chao ren / wen/tu, Gongxi Daye ; yi, Chen Yushu.', 'Xiao lu wen hua,', 2016, 'Fathers Juvenile fiction, Picture books for children, Chinese language materials');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (29, '0062386182, 9780062386182', 'Todd, Charles', 'No shred of evidence / Charles Todd.', 'William Morrow, an imprint of HarperCollinsPublishers,', 0, 'Rutledge Ian Fictitious character Fiction, Police Great Britain Fiction, Murder Investigation Fiction, Mystery fiction, Historical fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (30, '1419889974, 9781419889974', NULL, 'Sex and the city. Season 4 / HBO.', 'Home Box Office : Distributed by Warner Bros. Entertainment,', 0, 'Female friendship New York State New York Drama, Dating Social customs New York State New York Drama, Sex customs New York State New York Drama, New York N Y Social life and customs Drama, Television series, Television comedies, Fiction television programs, Video recordings for the hearing impaired');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (31, NULL, 'Lyon, Sidney Elizabeth, 1846-', 'Lyon memorial; Massachusetts families including descendants o the immigrants William Lyon of Roxbury, Peter Lyon of Dorchester, George Lyon of Dorchester.', 'Graham,', 1905, 'Lyons family');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (32, '0060223383, 0060223391, 0064430073', 'Hoban, Russell', 'A birthday for Frances / by Russell Hoban ; pictures by Lillian Hoban.', 'HarperCollins,', 1995, 'Birthdays Juvenile fiction, Badgers Juvenile fiction, Behavior Fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (33, '1596435410, 9781596435414', 'Raczka, Bob', 'Lemonade : and other poems squeezed from a single word / by Bob Raczka ; illustrated by Nancy Doniger.', 'Roaring Brook Press,', 2011, 'Word games Juvenile literature, Childrens poetry American, American poetry Juvenile literature');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (34, '0061119695, 0061119709, 9780061119699, 9780061119705', 'Avi, 1937-', 'Poppy and Ereth / Avi ; illustrated by Brian Floca.', 'HarperCollinsPublishers,', 2009, 'White footed mouse Fiction, Mice Juvenile fiction, Porcupines Juvenile fiction, Bats Juvenile fiction, Friendship Fiction, Adventure stories');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (35, NULL, 'United States. Maritime Commission', 'Report to Congress for the period of ... / United States Maritime Commission.', 'U.S. G.P.O.,', 0, 'Merchant marine United States Periodicals, Shipping United States Periodicals');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (36, '691074798', 'Berghahn, Volker R. (Volker Rolf), 1938-', 'America and the intellectual cold wars in Europe : Shepard Stone between philanthropy, academy, and diplomacy / Volker R. Berghahn.', 'Princeton University Press,', 2001, 'Stone Shepard, Cold War Public opinion, Public opinion Europe History 20th century, Ideology, Anti Americanism Europe, Economic assistance American Europe, United States Foreign public opinion European, United States Relations Europe, Europe Relations United States, United States Cultural policy, United States Foreign relations 1945 1989 Public opinion');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (37, NULL, NULL, 'Current diagnosis & treatment, surgery.', 'McGraw-Hill Medical', NULL, 'Surgery, Diagnosis Surgical Handbooks manuals etc, Surgery Operative Handbooks manuals etc');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (38, '156512927X, 9781565129276', 'De Sa, Anthony', 'Kicking the sky : a novel / Anthony De Sa.', 'Algonquin Books of Chapel Hill,', 2014, 'Boys Fiction, Portuguese Canada Fiction, Toronto Ont Fiction, Bildungsromans, Domestic fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (39, '1442401974, 9781442401976', 'Perlman, Willa', 'Good night, world / words by Willa Perlman ; pictures by Carolyn Fisher.', 'Beach Lane Books,', 2011, 'Stories in rhyme Juvenile fiction, Bedtime Juvenile fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (40, NULL, NULL, 'Charts and publications. 2, United States Pacific Coast, including Hawaii, Guam, and Samoa Islands.', 'National Oceanic and Atmospheric Administration, National Ocean Service,', NULL, 'Nautical charts Pacific Coast U S Catalogs Periodicals, Nautical charts Hawaii Catalogs Periodicals, Nautical charts Mariana Islands Catalogs Periodicals, Nautical charts Samoan Islands Catalogs Periodicals');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (41, '0316122173, 9780316122177', 'Spinelli, Jerry', 'Mama Seeton\'s whistle / by Jerry Spinelli ; art by LeUyen Pham.', 'Little, Brown and Company,', 2015, 'Whistling Juvenile fiction, Mother and child Juvenile fiction, Families Juvenile fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (42, '70115737', NULL, 'Handbook of structural concrete / edited by F.K. Kong ... [and others].', 'McGraw-Hill,', 1983, 'Concrete Handbooks manuals etc');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (43, '1682612384, 9781682612385', 'Robbins, Mel, 1968-', 'The 5 second rule : transform your life, work, and confidence with everyday courage / Mel Robbins.', 'Savio Republic,', 2017, 'Self esteem Psychological aspects, Courage Popular works, Motivation Psychology');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (44, '006224535X, 9780062245359', 'Murphy, Julie, 1985-', 'Side effects may vary / Julie Murphy.', 'Balzer + Bray, an imprint of HarperCollinsPublishers,', 0, 'Leukemia Juvenile fiction, Revenge Juvenile fiction, Interpersonal relations Juvenile fiction, Love Fiction, Friendship Fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (45, '1448825741, 144882737X, 1448827388, 9781448825745, 9781448827374, 9781448827381', 'Lynette, Rachel', 'Let\'s throw a St. Patrick\'s Day party! / Rachel Lynette.', 'PowerKids Press,', 2012, 'Saint Patricks Day decorations Juvenile literature, Saint Patricks Day Juvenile literature, Cooking Irish Juvenile literature, Childrens parties Juvenile literature, Parties');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (46, '375503862', 'Barker, Raffaella, 1964-', 'Hens dancing / Raffaella Barker.', 'Random House,', 2001, 'Single mothers Fiction, Mother and child Fiction, Norfolk England Fiction, Domestic fiction, Pastoral fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (47, '0670011487, 9780670011483', 'Carlson, Nancy L.', 'Henry and the bully / Nancy Carlson.', 'Viking,', 2010, 'Bullies Fiction, Mice Juvenile fiction, Animals Fiction, Schools Fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (48, '1410470857, 9781410470850', 'Pronzini, Bill', 'Strangers / Bill Pronzini.', 'Thorndike Press, a part of Gale, Cengage Learning,', 2014, 'Teenage boys Fiction, Rape Investigation Fiction, Rapists Fiction, Nameless Detective Fictitious character Fiction, Private investigators Nevada Fiction, Large type books, Suspense fiction, Mystery fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (49, '0807550809, 0807550817, 9780807550809, 9780807550816', 'Kit, Katy', 'Jasmine and the treasure chest / written by Katy Kit ; illustrated by Tom Knight..', 'Albert Whitman & Co.,', 2011, 'Mermaids Fiction, Buried treasure Fiction, Mystery and detective stories');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (50, '0807545503, 9780807545508', 'Daugherty, James, 1889-1974', 'Lincoln\'s Gettysburg address : a pictorial interpretation / painted by James Daugherty.', 'Albert Whitman & Co.,', 2013, 'Lincoln Abraham 1809 1865 Gettysburg address Juvenile literature, Gettysburg Battle of Gettysburg Pa 1863 Juvenile literature');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (51, '0471660868, 9780471660866', 'Casey, Susan (Susan Mary)', 'Kids inventing : a handbook for young inventors / Susan Casey.', 'John Wiley,', 2005, 'Inventions Juvenile literature, Children as inventors Juvenile literature, Inventors Juvenile literature');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (52, '747528241', NULL, 'New Scottish writing / edited by Harry Ritchie.', 'Bloomsbury Pub.,', 1996, 'English literature Scottish authors, English literature 20th century, Scotland Literary collections');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (53, '1302901648, 9781302901646', 'Caramagna, Joe', 'Avengers assemble. Civil war / based on the TV series written by Danielle Wolff, Jacob Semahn, Kevin Burke & Chris \"Doc\" Wyatt ; directed by Phil Pignotti & Tim Eldred ; adapted by Joe Caramagna ; art by Marvel Animation.', 'Marvel Worldwide, Inc., a subsidiary of Marvel Entertainment, LLC,', 0, 'Superheroes Comic books strips etc, Adventure and adventurers Comic books strips etc, Cartoons and comics, Comics Graphic works');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (54, '1250009707, 9781250009708', 'Watson, Roger (Museum curator)', 'Capturing the light : the birth of photography, a true story of genius and rivalry / Roger Watson and Helen Rappaport.', 'St. Martin\'s Press,', 2013, 'Daguerre Louis Jacques Mand‚ 1787 1851, Talbot William Henry Fox 1800 1877, Photographers France Biography, Photographers England Biography, Inventors France Biography, Inventors England Biography, Photography France History 19th century, Photography England History 19th century');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (55, '374161577', 'Haffner, Sebastian', 'Defying Hitler : a memoir / Sebastian Haffner ; translated by Oliver Pretzel.', 'Farrar, Straus and Giroux,', 2002, 'Haffner Sebastian, Historians Germany Biography, National socialism, Germany History 1918 1933');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (56, '1589238826, 9781589238824', 'Watanabe, Judi, 1963-', 'The complete photo guide to cardmaking / Judi Watanabe ; photographs: Rob Bostick and Judi Watanabe.', 'Creative Publishing International, an imprint of Quarto Publishing Group USA Inc.,', 0, 'Greeting cards, Paper work');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (57, NULL, 'Gray, Thomas, 1716-1771', 'Elegy written in a country churchyard.', 'A.J. St. Onge,', 1960, NULL);
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (58, NULL, 'Hughes, Thomas, 1759 or 60-1790.', 'A journal by Thos. Hughes for his amusement, & designed only for his perusal by the time he attains the age of 50 if he lives so long. (1778-1789) With an introd. by E. A. Benians.', 'University Press,', 1947, 'Hughes Thomas 1759 or 60 1790, Canada Description and travel, United States History Revolution 1775 1783 Prisoners and prisons, United States History Revolution 1775 1783 Personal narratives British');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (59, '0307978125, 030797815X, 0307978478, 9780307978127, 9780307978158, 9780307978479', 'Grey, Mini', 'Toys in space / by Mini Grey.', 'Alfred A. Knopf,', 2013, 'Toys Juvenile fiction, Storytelling Juvenile fiction, Night Juvenile fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (60, NULL, 'Presley, Elvis, 1935-1977', 'The wonder of you / Elvis with the Royal Philharmonic Orchestra.', 'RCA/Legacy,', 0, 'Popular music 2011 2020, Rock music 2011 2020, Rock music, Popular music');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (61, '810961873', 'Dabrowski, Magdalena', 'Aleksandr Rodchenko / Magdalena Dabrowski, Leah Dickerman, Peter Galassi ; with essays by Aleksandr Lavrentʹev and Varvara Rodchenko.', 'Museum of Modern Art,', 1998, 'Rodchenko Aleksandr Mikhailovich 1891 1956, Photography Artistic');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (62, '0765376474, 9780765376473', 'Schwab, Victoria', 'A gathering of shadows / V.E. Schwab.', 'Tor,', 2016, 'Magic Fiction, Contests Fiction, Fantasy fiction, Science fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (63, '5389031768, 9785389031760', NULL, 'Pokupal baran baranki / khudozhnik, Boris Trzheme︠t︡skiĭ.', '\"Makhaon\",', 2012, 'Childrens poetry Russian Juvenile literature, Russian language materials');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (64, '0545094682, 9780545094689', 'Peete, Holly Robinson, 1964-', 'Same but different : teen life on the autism express / Holly Robinson Peete, Ryan Elizabeth Peete, RJ Peete.', 'Scholastic Press,', 2016, 'Autistic children Juvenile fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (65, '1101997540, 9781101997543', 'Taylor, Mildred D.', 'Let the circle be unbroken / Mildred D. Taylor.', 'Puffin Books,', 2016, 'Logan family Fictitious characters Taylor Juvenile fiction, African Americans Juvenile fiction, Mississippi Juvenile fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (66, NULL, 'Aba Matthias Desta.', 'Kedamiha Letibeb Feriha / ʾAbā Mātéyās Desta.', '[Multicultural Books, distributor],', 2000, 'YaItyopya ortodoks tawahedo b‚ta kerestiyan, Ethiopian Orthodox Tewahedo Church, Christianity Ethiopia, Christian education Ethiopia');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (67, '1531700233, 9781531700232', NULL, 'Wild Kratts. Panda-monium / PBS Kids ; a Kratt Brothers Company/9 Story Entertainment production.', 'PBS Distribution,', 0, 'Giant panda Juvenile films, Animated television programs, Childrens television programs, Educational television programs, Television series, Video recordings for the hearing impaired');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (68, '1402778627, 9781402778629', 'Gershator, Phillis', 'Time for a hug / Phillis Gershator & Mim Green ; illustrated by David Walker.', 'Sterling Pub. Co.,', 2012, 'Stories in rhyme Juvenile fiction, Hugging Juvenile fiction, Rabbits Juvenile fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (69, '2253037400', 'Lévy, Bernard-Henri', 'La barbarie à visage humain / Bernard-Henri Lévy.', 'Grasset,', 0, 'Socialism History, Power Social sciences, Totalitarianism');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (70, '0374346356, 9780374346355', 'Sullivan, Sarah', 'Once upon a baby brother / Sarah Sullivan ; pictures by Tricia Tusa.', 'Farrar, Straus, Giroux,', 2010, 'Storytelling Juvenile fiction, Creative writing Juvenile fiction, Brothers and sisters Fiction, Babies Fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (71, NULL, 'Hassler, Warren W.', 'Commanders of the Army of the Potomac.', 'Louisiana State University Press,', 0, 'United States Army of the Potomac Biography, Generals United States, United States History Civil War 1861 1865 Regimental histories, United States History Civil War 1861 1865 Biography');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (72, '177046252X, 9781770462526', 'Jansson, Tove', 'Moomin and family life / Tove Jansson.', 'Drawn & Quarterly,', 2016, 'Moomins Fictitious characters Comic books strips etc, Cartoons and comics, Comics Graphic works');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (73, '184976414X, 9781849764148', 'Lewis, Emma, 1988-', 'The museum of me / Emma Lewis.', 'Tate Publishing,', 2016, 'Museums Juvenile fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (74, '1609807278, 9781609807276', 'Moss, Stanley', 'Almost complete poems / Stanley Moss.', 'Seven Stories Press,', 0, 'American poetry 20th century, Poetry');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (75, NULL, NULL, 'Orange is the new black. Season four / Tilted Productions ; Lionsgate Television.', 'Lionsgate,', 0, 'Federal Correctional Institution Danbury Conn Drama, Women prisoners Drama, Reformatories for women Drama, Television series, Television comedies, Fiction television programs, Video recordings for the hearing impaired');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (76, NULL, 'Architectural Publication Society', 'Detached essays and illustrations, issued during the years 1848-52.', 'Printed by T. Richards,', 1853, 'Architecture');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (77, '0451465393, 9780451465399', 'Scott, M. J. (Melanie Joy), 1971-', 'The shattered court : a novel of the four arts / M.J. Scott.', 'Roc,', 0, 'Witches Fiction, Magic Fiction, Man woman relationships Fiction, Fantasy fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (78, '1449436358, 9781449436353', 'Peirce, Lincoln', 'Big Nate. Great minds think alike / by Lincoln Peirce.', 'Andrews McMeel Publishing,', 0, 'Big Nate Comic books strips etc, Middle schools Comic books strips etc, Middle school students Comic books strips etc, Boys Comic books strips etc, Schools Comic books strips etc, Cartoons and comics, Graphic novels');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (79, '0756545188, 0756545358, 9780756545185, 9780756545352', 'Wittekind, Erika, 1980-', 'The big push : how popular culture is always selling / by Erika Wittekind.', 'Compass Point Books,', 2012, 'Consumer behavior Juvenile literature, Popular culture Marketing Juvenile literature');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (80, '0316078468, 9780316078467', 'Adams, Ansel, 1902-1984', 'Ansel Adams in the national parks : photographs from America\'s wild places / edited by Andrea G. Stillman.', 'Little, Brown,', 2010, 'Adams Ansel 1902 1984, National parks and reserves United States Pictorial works, Wilderness areas United States Pictorial works, Landscape photography United States');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (81, NULL, NULL, 'World aviation directory & aerospace database. Buyer\'s guide.', 'World Aviation Directory & Aerospace Database,', 0, 'Aeronautics Directories, Aerospace industries Directories, Astronautics Directories');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (82, NULL, 'Wied, Maximilian, Prinz von, 1782-1867', 'Maximilian, prince of Wied\'s Travels in the interior of North America, 1832-1834.', 'The A.H. Clark Company,', 1906, 'Indians of North America, Indians of North America Languages, Natural history United States, United States Description and travel');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (83, '1600853242, 9781600853241', NULL, 'Kaffe Fassett\'s quilts en Provence / featuring Roberta Horton ... [and others].', 'Taunton Press,', 2010, 'Patchwork Patterns, Quilting Patterns');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (84, '1683300076, 9781683300076', 'Gramling, Gary', 'The football fanbook / Gary Gramling ; design by Beth Bugler.', 'Liberty Street, an imprint of Time Inc. Books,', 2017, 'Football Miscellanea Juvenile literature, Football Statistics Juvenile literature');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (85, '1627794530, 9781627794534', 'Feldman, Suzanne, 1958-', 'Absalom\'s daughters : a novel / Suzanne Feldman.', 'Henry Holt and Company,', 2016, 'African American girls Fiction, Sisters Fiction, Racially mixed people Fiction, Families Fiction, Bildungsromans');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (86, '149670424X, 9781496704245', 'Kennedy, Jeffe, 1966-', 'The pages of the mind / Jeffe Kennedy.', 'Kensington Books,', 0, 'Marriages of royalty and nobility Fiction, Queens Fiction, Shapeshifting Fiction, Librarians Fiction, Fantasy fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (87, '0345475623, 9780345475626', 'Davis, Jim, 1945 July 28-', 'Garfield out to lunch / by Jim Davis.', 'Ballantine Books,', 2006, 'Garfield Fictitious character Comic books strips etc, Cats Comic books strips etc, Cartoons and comics, Comic books strips etc');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (88, '806974206', 'Kasahara, Kunihiko, 1941-', 'Amazing origami / Kunihiko Kasahara.', 'Sterling Pub.,', 2002, 'Origami');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (89, '1600592449, 9781600592447', 'Reason, Emily', 'Wheel throwing / Emily Reason.', 'Lark Books,', 2010, 'Pottery craft');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (90, '1622869621, 9781622869626', 'Hampton, Brenda (Brenda M.)', 'BFF\'s. 3 / Brenda Hampton.', 'Urban Books, LLC,', 0, 'African American women Fiction, Female friendship Fiction, Triangles Interpersonal relations Fiction, Urban fiction');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (91, NULL, 'United States Commission on Civil Rights.', 'Federal Title VI enforcement to insure nondiscrimination in federally assisted programs : a report of the U.S Commission on Civil Rights.', 'The Commission,', 0, 'Affirmative action programs United States Finance, Civil rights United States');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (92, '1608868036, 9781608868032', 'Stevenson, Noelle', 'Lumberjanes. [3], A terrible plan / written by Noelle Stevenson & Shannon Watters ; illustrated by Carolyn Nowak [and six others] ; colors by Maarta Laiho ; letters by Aubrey Aiese ; cover by Noelle Stevenson; created by Shannon Watters, Grace Ellis & Noelle Stevenson.', 'BOOM! Box, a division of Boom Entertainment, Inc.,', 2016, 'Teenage girls Comic books strips etc, Camps Comic books strips etc, Monsters Comic books strips etc, Cartoons and comics, Comics Graphic works, Graphic novels');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (93, NULL, NULL, 'Lake Chelan National Recreation Area : general management plan/environmental impact statement : supporting data studies / [National Park Service].', 'The Service,', 0, 'National parks and reserves Environmental aspects Washington State, Lake Chelan National Recreation Area Wash Environmental aspects');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (94, '076367432X, 9780763674328', NULL, 'Ruff Ruffman\'s 44 favorite science activities.', 'Candlewick Entertainment, an imprint of Candlewick Press,', 2015, 'Science Miscellanea Juvenile literature, Science Experiments Juvenile literature, Science projects Juvenile literature');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (95, '0785198695, 9780785198697', 'David, Peter (Peter Allen)', 'Future imperfect : Warzones! / writer, Peter David ; penciler, Greg Land ; inker, Jay Leisten ; colorist, Nolan Woodard ; artist, Daniel Valadez ; color artist, David Curiel ; cover art, Greg Land, Nolan Woodard, Francesco Francavilla.', 'Marvel Comics,', 2015, 'Hulk Fictitious character Comic books strips etc, Imaginary wars and battles Comic books strips etc, Graphic novels, Comics Graphic works');
INSERT INTO `Books` (`book_id`, `isbn`, `author`, `title`, `publisher`, `publication_year`, `subjects`) VALUES (96, NULL, NULL, 'Infantry.', 'U.S. Army Infantry School,', 0, 'Infantry Periodicals, Military art and science Periodicals');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;